[package]
name = "pgen"
version = "0.1.0"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"

[workspace]
members = ["wtf"]

[dependencies]
regex = "1.3.1"
thiserror = "1.0.9"
prettytable-rs = "0.8.0"
symbol = "0.1.7"

[dev-dependencies]
proptest = "0.9.5"
