// Code was generated by pgen
use std::io::Read;
use pgen::regex::RegexSet;
const PATTERNS: &[&'static str] = &[
    "\\(",
    "\\d+",
    "\\*",
    "\\)",
    "\\+",
];
pub struct Parser {
    regex_set: RegexSet,
}
impl Parser {
    pub fn new() -> Self {
        let regex_set = RegexSet::new(PATTERNS.clone()).unwrap();
        Parser { regex_set }
    }
    pub fn parse_Expr(&self, input: impl AsRef<str>) {
        let input = input.as_ref();
    }
}
